### ISSUE TITLE
Travis test fails

### ISSUE THREAD

**Issue by gregtucker** [landlab/tutorials#52] opened 2019-09-23 01:37 UTC
The travis tests seem to be generating

ImportError: no module named landlab

@mcflugen any ideas?

**Comment by mcflugen** [comment] 2019-09-23 05:04
@gregtucker The problem is that *landlab* is not being installed correctly when not on the *release* branch. When running the tests on *release*, *landlab* is installed with `conda install landlab`. However, when on another branch, landlab is cloned and installed from source (you can see this in [`.travis.yaml`](https://github.com/landlab/tutorials/blob/07f4d7d4765fbd559c4c9ca1540371b5da61bc6e/.travis.yml#L37)). This is whey the PR passes (it's being merged into *release*) but the push doesn't.

I'll have to have a look at this tomorrow to see what the best way to fix this is.

**Comment by gregtucker** [comment] 2019-09-24 22:57
@mcflugen Can safely ignore it then, since the pr gets tested properly?

**Comment by kbarnhart** [comment] 2019-10-14 17:25
@gregtucker @mcflugen I fixed this in #67

**Closed as completed by kbarnhart** 2019-10-14 17:25 UTC
